function savePBS(fname,regname,username,N,P,GB,catalog_name)
mpath = '/nfs/turbo/umms-cgalban/Matlab';
fid = fopen(fname,'w');
if fid
    fprintf(fid,...
        ['####  PBS preamble\n\n',...
         '#PBS -N lungReg_%s\n',...                     Job Name
         '#PBS -M %s@umich.edu\n',...                   User email address
         '#PBS -m ae\n\n',...                           Notification option: n (none), b (begins), e (ends), a (aborts)
         '#PBS -A cgalban_fluxod\n',...                 Account
         '#PBS -l qos=flux\n',...                       Do not change
         '#PBS -q flux\n',...                           Specifies which queue
         '#PBS -l nodes=%u:ppn=%u,pmem=%ugb\n',...      nodes (machines), ppn (processors/node), pmem (memory/processor)
         '#PBS -l walltime=8:00:00\n',...               Maximum processing time (dd:hh:mm:ss)
         '#PBS -j oe\n',...                             Combines output and error streams
         '#PBS -V\n\n',...                              Sets node environment to current effective environment
         '####  End PBS preamble\n\n',...
         'if [ -s "$PBS_NODEFILE" ] ; then\n',...
         '    echo "Running on"\n',...
         '    uniq -c $PBS_NODEFILE\n',...
         'fi\n\n',...
         'if [ -d "$PBS_O_WORKDIR" ] ; then\n',...
         '    cd $PBS_O_WORKDIR\n',...
         '    echo "Running from $PBS_O_WORKDIR"\n',...
         'fi\n\n',...
         '#  Put your job commands after this line\n',...
         'matlab -nodisplay -r "addpath(genpath(''%s'')) ; batch_fluxLungReg(''%s'',''%s'') ; exit"'],....
         regname,username,mpath,N,P,GB,username,fluxPath(catalog_name));
     fclose(fid);
end

function str = fluxPath(str)
str = strsplit(str,filesep);
i = find(strcmp('umms-cgalban',str),1);
str = fullfile('/nfs/turbo/',str{i:end});