% Function to initialize Elastix parameter structure to defaults
function s = initAffineParStruct

s = struct('ImageTypes',...
              struct('FixedInternalImagePixelType', 'float',...
                     'FixedImageDimension',         3,...
                     'MovingInternalImagePixelType','float',...
                     'MovingImagedimension',        3,...
                     'UseDirectionCosines',         'false',...
                     'ResultImageFormat',           'mhd'),...
           'Outputs',...
              struct('WriteTransformParametersEachIteration','false',...
                     'WriteTransformParametersEachResolution','false',...
                     'WriteResultImageAfterEachResolution','false',...
                     'WriteResultImage','true',...
                     'ShowExactMetricValue','false',...
                     'ErodeFixedMask','false',...
                     'ErodeMovingMask','false'),...
           'Pyramid',...
              struct('NumberOfResolutions',3,...
                     'FixedImagePyramid','FixedSmoothingImagePyramid',...
                     'FixedImagePyramidSchedule',[4 4 4 2 2 2 1 1 1],...
                     'MovingImagePyramid','MovingSmoothingImagePyramid',...
                     'MovingImagePyramidSchedule',[4 4 4 2 2 2 1 1 1]),...
           'Registration',...
              struct('Registration','MultiResolutionRegistration'),...
           'Metric',...
              struct('Metric','AdvancedMattesMutualInformation',...
                     'UseFastAndLowMemoryVersion','false',...
                     'UseJacobianPreconditioning','true',...
                     'FiniteDifferenceDerivative','false',...
                     'NumberOfHistogramBins',32,...
                     'NumberOfFixedHistogramBins',32,...
                     'NumberOfMovingHistogramBins',32,...
                     'FixedLimitRangeRatio',0,...
                     'MovingLimitRangeRatio',0,...
                     'FixedKernelBSplineOrder',1,...
                     'MovingKernelBSplineOrder',3),...
           'Optimizer',...
              struct('Optimizer','StandardGradientDescent',...
                     'NumberOfSamplesForSelfHessian',100000,...
                     'MaxBandCovSize',192,...
                     'NumberOfBandStructureSamples',10,...
                     'SigmoidInitialTime',0,...
                     'SigmoidMax',1,...
                     'SigmoidMin',-0.8,...
                     'SigmoidScale',1e-5,...
                     'SigmoidScaleFactor',0.1,...
                     'MaximumStepLength',[1,0.5,0.5,0.5],...
                     'NumberOfGradientMeasurements',0,...
                     'NumberOfJacobianMeasurements',1000,...
                     'NumberOfSamplesForExactGradient',100000,...
                     'MaximumNumberOfIterations',1000,...
                     'MaximumNumberOfSamplingAttempts',10,...
                     'AutomaticParameterEstimation','false',...
                     'ASGDParameterEstimationMethod','Original',...
                     'UseAdaptiveStepSizes','true',...
                     'SP_a',[100,50,10],...  % SP_ parameters not used if AutomaticParameterEstimation is "true"
                     'SP_alpha',0.602,...
                     'SP_A',50),...
           'InterpolatorResampler',...
              struct('Interpolator','LinearInterpolator',... % Interp during optim (Linear faster than 1st-order BSpline)
                     'ResampleInterpolator','FinalBSplineInterpolator',... % Final interpolator after optimization
                     'FinalBSplineInterpolationOrder',3,...
                     'Resampler','DefaultResampler'),...
           'ImageSampler',...
              struct('CheckNumberOfSamples','true',...
                     'ImageSampler','Full',...
                     'NumberOfSpatialSamples',2000,...
                     'NewSamplesEveryIteration','true',...
                     'UseRandomSampleRegion','false'),...
           'Transform',...
              struct('Transform','EulerTransform',...
                     'AutomaticTransformInitialization','true',...
                     'AutomaticTransformInitializationMethod','GeometricalCenter',...
                     'AutomaticScalesEstimation','false',...
                     'Scales',[1000,1000,1000,1,1,1],...
                     'FinalGridSpacingInVoxels',[10,10,10],...
                     'GridSpacingSchedule',[8,4,2,1],...
                     'HowToCombineTransforms','Compose',...
                     'BSplineTransformSplineOrder',3,...
                     'UseCyclicTransform','false'));

