% CMIclass function
function [MF,labels] = calcMF(self,~,~)
% Calculate Minkowski Functionals

MF = []; labels = {};

% If a GUI call, ask for user input:
str = {'Image index (0=VOI)',                       num2str(self.vec);
       'Thresholds (vector of image values)',       '';...
       'Threshold mode (p if percentiles, then <,>,>=,<=,==)','>';...
       'Window Size ("inf" for overall analysis)',  'inf inf inf';...
       'Apply VOI to analysis? (y/n)',              'y';...
       'Non-VOI value (1/0)',                       '0'};
answer = inputdlg(str(:,1),'Minkowski Functionals',1,str(:,2));
if isempty(answer)
    return;
else
    [MF,labels] = self.img.calcMF(str2double(answer{1}),...
                                  str2num(answer{2}),...
                                  str2num(answer{4}),...
                                  'ApplyMask',strcmp(answer{5},'y'),...
                                  'tmode',answer{3},...
                                  'defVal',logical(str2double(answer{6})));
    assignin('base','MFvals',MF);
    assignin('base','MFlabels',labels);
end


