% RegClass function
function h = regFig(self)
%regFig : Initializes image coregistration figure programmatically
%   * positions, fonts, etc. set on OS X (may need adjusting for Windows)
%   * generated in code because tabs not available in GUIDE

scrsz = get(groot,'MonitorPositions');
scrsz = scrsz(scrsz(:,1)==1,3:4);
figsz = [512,600];
if ispc
    figborder = 5; % Figure border is 5 points wide
    topbar = 17; 
else
    figborder = 0; % Mac border is 0 pixels wide
    topbar = 17;
end

h.regFig = figure('Units','points',...
                  'Resize','off',...
                  'Position',[scrsz(1)-figsz(1)-figborder,...
                              scrsz(2)-figsz(2)-figborder-topbar,...
                              figsz],...
                  'Color',[0.5,0.5,0.5],...
                  'Tag','regFig','Name','CMIreg',...
                  'ToolBar','none','Menubar','none','DockControls','off');
set(h.regFig,'defaultuicontrolUnits','normalized','defaultuitableUnits','normalized',...
    'defaultuicontrolFontSize',12);

h.tabGrp = uitabgroup(h.regFig,'Position',[0.01,0.01,0.98,0.98],'Tag','tabGrp');

h.tab_Opts = uitab(h.tabGrp,'Title','Options','Tag','tab_Opts');

    h.text_Odir = uicontrol(h.tab_Opts,'Style','text','Tag','text_Odir',...
        'String','Output Directory: ','Position',[0.01,0.94,0.2,0.04]);
    h.button_odir = uicontrol(h.tab_Opts,'Style','pushbutton','Tag','button_odir',...
        'String','Browse','Position',[0.01,0.91,0.19,0.045],'Callback',@self.setOdir);
    h.edit_Odir = uicontrol(h.tab_Opts,'Style','edit','Tag','edit_odir','Max',2,...
        'String','','FontSize',10,'Position',[0.22,0.9,0.77,0.09],'Callback',@self.setOdir);
    
    h.table_opts = uitable(h.tab_Opts,'Tag','table_opts','Enable','on',...
        'Position',[0.01,0.56,0.55,0.33],'CellEditCallback',@self.UDpreproc,...
        'RowName',{'Min:','Max:','FiltX:','FiltY:','FiltZ:',...
                   'DilateX:','DilateY:','DilateZ:','UnMaskVal:'},...
        'ColumnName',{'Fixed','Moving'},'ColumnEditable',true,...
        'Data',num2cell([self.clamp';self.filtN';self.dilateN';self.unmaskval]));
           
    h.text_preprocInfo = uicontrol(h.tab_Opts,'Style','text','Tag','text_preprocInfo',...
        'String',{'Operation Order:';'1. Filter';'2. Min/Max';'3. Unmasked Values';'4. HistEq'},...
        'Position',[0.6,0.73,0.3,0.16],'HorizontalAlignment','left');
    
    h.text_preFilter = uicontrol(h.tab_Opts,'Style','text','Tag','text_preFilter',...
        'HorizontalAlignment','right','String','Filter Type: ','Position',[0.61,0.66,0.13,0.04]);
    h.popup_filterType = uicontrol(h.tab_Opts,'Style','popupmenu','Tag','popup_filterType',...
        'Position',[0.725,0.66,0.22,0.04],'Callback',@self.UDpreproc,...
        'String',{'Gaussian','Median','Wiener'},'Value',2);
        
    h.checkbox_histeq = uicontrol(h.tab_Opts,'Style','checkbox','Tag','checkbox_histeq',...
        'String','Histogram Equalization','Value',self.histeq,'Position',[0.6,0.62,0.4,0.04],...
        'Callback',@self.UDpreproc);
    
    h.text_Qnum = uicontrol(h.tab_Opts,'Style','text','Tag','text_Qnum',...
        'String','# of jobs:','Position',[0.6,0.56,0.11,0.04],...
        'HorizontalAlignment','left');
    h.edit_Qnum = uicontrol(h.tab_Opts,'Style','edit','Tag','edit_Qnum',...
        'String',num2str(self.qnum),'FontSize',12,'Position',[0.71,0.56,0.1,0.04],...
        'Callback',@self.setQnum);
    
    h.text_Qfile = uicontrol(h.tab_Opts,'Style','text','Tag','text_Qfile',...
        'String','Queue File: ','Position',[0.01,0.5,0.2,0.04]);
    h.button_Qfile = uicontrol(h.tab_Opts,'Style','pushbutton','Tag','button_Qfile',...
        'String','Browse','Position',[0.18,0.5,0.15,0.045],'Callback',@self.setQfile);
    h.button_Qupdate = uicontrol(h.tab_Opts,'Style','pushbutton','Tag','button_Qupdate',...
        'String','Update','Position',[0.32,0.5,0.14,0.045],'Callback',@self.Qupdate);
    h.text_QupdateP = uicontrol(h.tab_Opts,'Style','text','Tag','text_QupdateP',...
        'String','Last updated: ','Position',[0.46,0.5,0.2,0.04],'HorizontalAlignment','left');
    h.text_Qupdate = uicontrol(h.tab_Opts,'Style','text','Tag','text_Qupdate',...
        'String','','Position',[0.62,0.49,0.37,0.04],'HorizontalAlignment','left');
    
    h.edit_Qfile = uicontrol(h.tab_Opts,'Style','edit','Tag','edit_Qfile','Max',2,...
        'String',self.qfile,'FontSize',10,'Position',[0.01,0.45,0.98,0.045],...
        'Callback',@self.setQfile);
    
    h.table_queue = uitable(h.tab_Opts,'Tag','table_queue','Enable','on',...
        'Position',[0.01,0.01,0.98,0.44],'CellEditCallback',@self.Qupdate,...
        'ColumnName',{'#','Name','exec'},'ColumnEditable',[true,false,false],...
        'ColumnWidth',{30,300,5000});
    
h.tab_T0 = uitab(h.tabGrp,'Title','Initial Transform','Tag','tab_T0');

    h.text_ref = uicontrol(h.tab_T0,'Style','Text','Tag','text_ref','String','Reference',...
        'Position',[0.135,0.95,0.2,0.03],'FontSize',14);
    h.list_ref = uicontrol(h.tab_T0,'Style','Listbox','Tag','list_ref','Max',2,...
        'Position',[0.01,0.6,0.47,0.35]);
    h.button_deleteRef = uicontrol(h.tab_T0,'Style','pushbutton','Tag','button_deleteRef',...
        'Position',[0.01,0.56,0.15,0.04],'String','Delete','Callback',@self.delPoints);
    h.button_loadRef = uicontrol(h.tab_T0,'Style','pushbutton','Tag','button_loadRef',...
        'Position',[0.17,0.56,0.15,0.04],'String','Load','Callback',@self.loadPoints);
    h.button_saveRef = uicontrol(h.tab_T0,'Style','pushbutton','Tag','button_saveRef',...
        'Position',[0.33,0.56,0.15,0.04],'String','Save','Callback',@self.savePoints);
    
    h.text_hom = uicontrol(h.tab_T0,'Style','Text','Tag','text_hom','String','Homologous',...
        'Position',[0.665,0.95,0.2,0.03],'FontSize',14);
    h.list_hom = uicontrol(h.tab_T0,'Style','Listbox','Tag','list_hom',...
        'Position',[0.52,0.6,0.47,0.35],'Max',2);
    h.button_deleteHom = uicontrol(h.tab_T0,'Style','pushbutton','Tag','button_deleteHom',...
        'Position',[0.52,0.56,0.15,0.04],'String','Delete','Callback',@self.delPoints);
    h.button_loadHom = uicontrol(h.tab_T0,'Style','pushbutton','Tag','button_loadHom',...
        'Position',[0.68,0.56,0.15,0.04],'String','Load','Callback',@self.loadPoints);
    h.button_saveHom = uicontrol(h.tab_T0,'Style','pushbutton','Tag','button_saveHom',...
        'Position',[0.84,0.56,0.15,0.04],'String','Save','Callback',@self.savePoints);
    
    h.text_tform = uicontrol(h.tab_T0,'Style','text','Tag','text_tform',...
        'Position',[0.4,0.51,0.2,0.03],'HorizontalAlignment','center',...
        'String','Transform Type:');
    h.popup_Transforms = uicontrol(h.tab_T0,'Style','popupmenu','Tag','popup_Transforms',...
        'Position',[0.35,0.44,0.3,0.06],...
        'String',{'NONE','Translation','Euler','Similarity','Affine','Warp'});
    
    h.text_T0defVal = uicontrol(h.tab_T0,'Style','text','Tag','text_T0defVal',...
        'Position',[0.4,0.415,0.2,0.03],'HorizontalAlignment','center',...
        'String','Default Value:');
    h.edit_T0defVal = uicontrol(h.tab_T0,'Style','edit','Tag','edit_T0defVal',...
        'Position',[0.375,0.37,0.25,0.05],'String',num2str(self.T0defVal),...
        'Callback',@self.setT0DefVal);
    
    h.button_pts2tform = uicontrol(h.tab_T0,'Style','pushbutton','Tag','button_pts2tform',...
        'Position',[0.01,0.47,0.25,0.05],'String','Pts2Tform','Callback',@self.pts2M);
    h.button_manTform = uicontrol(h.tab_T0,'Style','pushbutton','Tag','button_manTform',...
        'Position',[0.01,0.42,0.25,0.05],'String','Manual Input','Callback',@self.manTform);
    h.button_VOI2tform = uicontrol(h.tab_T0,'Style','pushbutton','Tag','button_VOI2tform',...
        'Position',[0.01,0.37,0.25,0.05],'String','Match VOIs','Callback',@self.VOI2Tform);
    h.button_oneshot = uicontrol(h.tab_T0,'Style','pushbutton','Tag','button_oneshot',...
        'Position',[0.75,0.37,0.24,0.15],'String','OneShot','FontSize',18,...
        'BackgroundColor',[0.5,1,1],'Callback',@self.oneshot);
    
    % Show transform values for set transform:
    h.edit_a11 = uicontrol(h.tab_T0,'Style','edit','Tag','edit_a11',...
        'Position',[0.05,0.27,0.2,0.05],'String','1','Callback',@self.setT,...
        'Enable','off');
    h.edit_a12 = uicontrol(h.tab_T0,'Style','edit','Tag','edit_a12',...
        'Position',[0.27,0.27,0.2,0.05],'String','0','Callback',@self.setT,...
        'Enable','off');
    h.edit_a13 = uicontrol(h.tab_T0,'Style','edit','Tag','edit_a13',...
        'Position',[0.49,0.27,0.2,0.05],'String','0','Callback',@self.setT,...
        'Enable','off');
    h.edit_a21 = uicontrol(h.tab_T0,'Style','edit','Tag','edit_a21',...
        'Position',[0.05,0.21,0.2,0.05],'String','0','Callback',@self.setT,...
        'Enable','off');
    h.edit_a22 = uicontrol(h.tab_T0,'Style','edit','Tag','edit_a22',...
        'Position',[0.27,0.21,0.2,0.05],'String','1','Callback',@self.setT,...
        'Enable','off');
    h.edit_a23 = uicontrol(h.tab_T0,'Style','edit','Tag','edit_a23',...
        'Position',[0.49,0.21,0.2,0.05],'String','0','Callback',@self.setT,...
        'Enable','off');
    h.edit_a31 = uicontrol(h.tab_T0,'Style','edit','Tag','edit_a31',...
        'Position',[0.05,0.15,0.2,0.05],'String','0','Callback',@self.setT,...
        'Enable','off');
    h.edit_a32 = uicontrol(h.tab_T0,'Style','edit','Tag','edit_a32',...
        'Position',[0.27,0.15,0.2,0.05],'String','0','Callback',@self.setT,...
        'Enable','off');
    h.edit_a33 = uicontrol(h.tab_T0,'Style','edit','Tag','edit_a33',...
        'Position',[0.49,0.15,0.2,0.05],'String','1','Callback',@self.setT,...
        'Enable','off');
    h.edit_t1 = uicontrol(h.tab_T0,'Style','edit','Tag','edit_t1',...
        'Position',[0.71,0.27,0.2,0.05],'String','0','Callback',@self.setT,...
        'Enable','off');
    h.edit_t2 = uicontrol(h.tab_T0,'Style','edit','Tag','edit_t2',...
        'Position',[0.71,0.21,0.2,0.05],'String','0','Callback',@self.setT,...
        'Enable','off');
    h.edit_t3 = uicontrol(h.tab_T0,'Style','edit','Tag','edit_t3',...
        'Position',[0.71,0.15,0.2,0.05],'String','0','Callback',@self.setT,...
        'Enable','off');
    
    h.checkbox_useExistingT = uicontrol(h.tab_T0,'Style','checkbox',...
        'Tag','checkbox_useExistingT','String','Use This Tform:',...
        'Position',[0.1,0.1,0.23,0.04],'Callback',@self.setTchk);
    h.text_currTform = uicontrol(h.tab_T0,'Style','text','tag','text_currTform',...
        'String','[None]','Position',[0.34,0.094,0.65,0.04],'HorizontalAlignment','left');
    
    
h.tab_Guess = uitab(h.tabGrp,'Title','Guess','Tag','tab_Guess');
    
    h.text_Tguess = uicontrol(h.tab_Guess,'Style','text','Tag','text_Tguess',...
        'Position',[0.01,0.88,0.98,0.1]);
    set(h.text_Tguess,'String',textwrap(h.text_Tguess,...
        {'Use existing transform as initial guess for current Elastix setup.',...
         ['Select which transforms in the queue to use. (i.e. if you are using an ',...
          'initial transform you might not want to use the InitialTransform.txt in the queue).'],...
         '* Transforms are applied from bottom to top after InitialTransform.'},86)) 
     
    h.table_Tguess = uitable(h.tab_Guess,'Tag','table_Tguess','Enable','on',...
        'Position',[0.01,0.38,0.98,0.48],'CellEditCallback',@self.setTguess,...
        'ColumnName',{'Select','Name','Path'},'ColumnEditable',[true,false,false],...
        'ColumnWidth',{50,300,5000},'ColumnFormat',{'logical','char','char'});
    h.button_TGload = uicontrol(h.tab_Guess,'Style','pushbutton','Tag','button_TGload',...
        'String','Load','Position',[0.01,0.31,0.15,0.05],'Callback',@self.setTguess);
    h.button_TGclear = uicontrol(h.tab_Guess,'Style','pushbutton','Tag','button_TGclear',...
        'String','Clear','Position',[0.17,0.31,0.15,0.05],'Callback',@self.setTguess);
    
h.tab_Elx = uitab(h.tabGrp,'Title','Elastix','Tag','tab_Elx');

    h.text_files = uicontrol(h.tab_Elx,'Style','text','HorizontalAlignment','right',...
        'Tag','text_files','String','Files: ','Position',[0.01,0.93,0.15,0.04]);
    h.button_LOAD = uicontrol(h.tab_Elx,'Style','pushbutton','Tag','button_LOAD',...
        'Position',[0.16,0.935,0.15,0.05],'String','LOAD','Callback',@self.loadElxPar);
    h.button_SAVE = uicontrol(h.tab_Elx,'Style','pushbutton','Tag','button_SAVE',...
        'Position',[0.32,0.935,0.15,0.05],'String','SAVE','Enable','off',...
        'Callback',@self.saveElxPar);
    
    h.text_defs = uicontrol(h.tab_Elx,'Style','text','Tag','text_defs',...
        'String','Defaults: ','Position',[0.01,0.88,0.15,0.04],...
        'HorizontalAlignment','right');
    h.button_addTform = uicontrol(h.tab_Elx,'Style','pushbutton','Tag','button_addTform',...
        'Position',[0.16,0.885,0.15,0.05],'String','Add','Callback',@self.UDschedule);
    h.button_removeTform = uicontrol(h.tab_Elx,'Style','pushbutton','Tag','button_removeTform',...
        'Position',[0.32,0.885,0.15,0.05],'String','Remove','Enable','off',...
        'Callback',@self.UDschedule);
    
    h.text_nres = uicontrol(h.tab_Elx,'Style','text','Tag','text_nres',...
        'Position',[0.01,0.83,0.1,0.04],'HorizontalAlignment','right','String','# Res: ');
    h.edit_nres = uicontrol(h.tab_Elx,'Style','edit','Tag','edit_nres',...
        'Position',[0.11,0.835,0.1,0.04],'String','','Enable','off','Callback',@self.UDschedule);
    h.text_defVal = uicontrol(h.tab_Elx,'Style','text','Tag','text_defVal',...
        'Position',[0.27,0.83,0.1,0.04],'String','Def Val: ','HorizontalAlignment','right',...
        'Callback',@self.UDschedule);
    h.edit_defVal = uicontrol(h.tab_Elx,'Style','edit','Tag','edit_defVal',...
        'Position',[0.37,0.835,0.1,0.04],'String','','Callback',@self.UDschedule);
    
    h.listbox_Tforms = uicontrol(h.tab_Elx,'Style','listbox','Tag','listbox_Tforms',...
        'Position',[0.01,0.62,0.46,0.2],'Callback',@self.selectTform);
    h.button_scales = uicontrol(h.tab_Elx,'Style','pushbutton','Tag','button_scales',...
        'Position',[0.01,0.57,0.22,0.04],'String','Scales','Enable','off',...
        'Callback',@self.UDschedule);
    h.button_AllParameters = uicontrol(h.tab_Elx,'Style','pushbutton','Tag','button_AllParameters',...
        'Position',[0.24,0.57,0.22,0.04],'String','All Parameters','Enable','off',...
        'Callback',@self.allParameters);
    
    h.text_Sampler = uicontrol(h.tab_Elx,'Style','text','Tag','text_Sampler',...
        'String','Sampler: ','Position',[0.5,0.93,0.12,0.04],'HorizontalAlignment','right');
    h.popup_Sampler = uicontrol(h.tab_Elx,'Style','popupmenu','Tag','popup_Sampler',...
        'Position',[0.62,0.935,0.35,0.04],'Enable','off','Callback',@self.UDschedule,...
        'String',{'RandomSparseMask','RandomCoordinate','Full','Random','Grid'});
    h.text_Metric = uicontrol(h.tab_Elx,'Style','text','Tag','text_Metric',...
        'String','Metric: ','Position',[0.5,0.89,0.12,0.04],'HorizontalAlignment','right');
    h.popup_Metric = uicontrol(h.tab_Elx,'Style','popupmenu','Tag','popup_Metric',...
        'Position',[0.62,0.895,0.35,0.04],'Value',3,'Enable','off','Callback',@self.UDschedule,...
        'String',{'Sum of Squared Diff','Norm Correlation','Mutual Information','Nomr Mutual Info'},...
        'UserData',{'AdvancedMeanSquares','AdvancedNormalizedCorrelation',...
                    'AdvancedMattesMutualInformation','NormalizedMutualInformation'});
    
    h.checkbox_BEpenalty = uicontrol(h.tab_Elx,'Style','checkbox','Tag','checkbox_BEpenalty',...
        'Position',[0.6,0.855,0.25,0.04],'String','Bending Energy','Enable','off',...
        'Callback',@self.UDschedule);
    h.edit_BEpenaltyAmt = uicontrol(h.tab_Elx,'Style','edit','Tag','edit_BEpenaltyAmt',...
        'Position',[0.85,0.855,0.1,0.04],'Enable','off','Callback',@self.UDschedule);
    
    h.text_finalGrid = uicontrol(h.tab_Elx,'Style','text','Tag','text_finalGrid',...
        'String','Final Grid: ','Position',[0.5,0.8,0.15,0.04]);
    h.edit_finalGridX = uicontrol(h.tab_Elx,'Style','edit','Tag','edit_finalGridX',...
        'Position',[0.65,0.805,0.1,0.04],'Enable','off','Callback',@self.UDschedule);
    h.edit_finalGridY = uicontrol(h.tab_Elx,'Style','edit','Tag','edit_finalGridY',...
        'Position',[0.76,0.805,0.1,0.04],'Enable','off','Callback',@self.UDschedule);
    h.edit_finalGridZ = uicontrol(h.tab_Elx,'Style','edit','Tag','edit_finalGridZ',...
        'Position',[0.87,0.805,0.1,0.04],'Enable','off','Callback',@self.UDschedule);
    
    h.text_interp = uicontrol(h.tab_Elx,'Style','text','Tag','text_interp',...
        'String','Final Interp: ','Position',[0.5,0.75,0.15,0.04]);
    h.popup_interp = uicontrol(h.tab_Elx,'Style','popupmenu','Tag','popup_interp',...
        'Position',[0.65,0.755,0.32,0.04],'Enable','off','Callback',@self.UDschedule,...
        'String',{'Nearest','Linear','BSpline-3'},...
        'UserData',{'FinalNearestNeighborInterpolator','FinalLinearInterpolator',...
                    'FinalBSplineInterpolator'});
    
    h.checkbox_jac = uicontrol(h.tab_Elx,'Style','checkbox','Tag','checkbox_jac',...
        'Position',[0.47,0.71,0.27,0.04],'String','| Jacobian |','Callback',@self.UDschedule);
    h.checkbox_jacmat = uicontrol(h.tab_Elx,'Style','checkbox','Tag','checkbox_jacmat',...
        'Position',[0.47,0.67,0.27,0.04],'String','Jacobian Matrix','Callback',@self.UDschedule);
    h.checkbox_def = uicontrol(h.tab_Elx,'Style','checkbox','Tag','checkbox_def',...
        'Position',[0.47,0.63,0.27,0.04],'String','Deformation Fields','Callback',@self.UDschedule);
    h.checkbox_saveIntermediates = uicontrol(h.tab_Elx,'Style','checkbox',...
        'Tag','checkbox_saveIntermediates','Position',[0.47,0.59,0.27,0.04],...
        'String','Save Intermediates','Callback',@self.UDschedule);
    
    h.checkbox_Tvoi = uicontrol(h.tab_Elx,'Style','checkbox','Tag','checkbox_Tvoi',...
        'Position',[0.75,0.71,0.22,0.04],'String','Tfx VOI','Callback',@self.UDschedule);
    h.checkbox_Tsurf = uicontrol(h.tab_Elx,'Style','checkbox','Tag','checkbox_Tvoi',...
        'Position',[0.75,0.67,0.22,0.04],'String','Tfx Surface','Callback',@self.UDschedule);
    
    h.button_autoConfig = uicontrol(h.tab_Elx,'Style','pushbutton','Tag','button_autoConfig',...
        'String','Auto-SP_a','Position',[0.82,0.58,0.16,0.07],'Callback',@self.autoConfig);
    
    h.table_schedule = uitable(h.tab_Elx,'Tag','table_schedule','Enable','off',...
        'Position',[0.01,0.09,0.98,0.48],'CellEditCallback',@self.UDschedule,...
        'RowName',{'fX','fY','fZ','mX','mY','mZ','Iterations','SP_A','SP_a',...
        'Nsamples','gridX','gridY','gridZ'},'ColumnEditable',true,...
        'UserData',{'FixedImagePyramidSchedule','FixedImagePyramidSchedule','FixedImagePyramidSchedule',...
                    'MovingImagePyramidSchedule','MovingImagePyramidSchedule','MovingImagePyramidSchedule',...
                    'MaximumNumberOfIterations','SP_A','SP_a','NumberOfSpatialSamples',...
                    'GridSpacingSchedule','GridSpacingSchedule','GridSpacingSchedule'});
    
    h.checkbox_wait = uicontrol(h.tab_Elx,'Style','checkbox','Tag','checkbox_wait',...
        'Position',[0.68,0.03,0.3,0.04],'String','Run independently','Value',1,...
        'Callback',@self.UDschedule);
                
    h.button_Start = uicontrol(h.tab_Elx,'Style','pushbutton','Tag','button_Start',...
        'BackgroundColor',[0,0.8,0],'String','Start','FontWeight','bold','FontSize',18,...
        'Position',[0.35,0.01,0.3,0.08],'Callback',@self.runElx);
    
    h.button_Queue = uicontrol(h.tab_Elx,'Style','pushbutton','Tag','button_Queue',...
        'BackgroundColor',[0,0.5,0],'FontWeight','bold','FontSize',18,...
        'String','Queue','Position',[0.05,0.01,0.3,0.08],'Callback',@self.runElx);
    
    
h.tab_Tfx = uitab(h.tabGrp,'Title','Transformix','Tag','tab_Tfx');

    h.text_descript = uicontrol(h.tab_Tfx,'Style','text','Tag','text_descript',...
        'Position',[0.01,0.9,0.98,0.09],'String',['These options are for a applying '...
        'an existing transform to images. The checkbox on the left side of the table '...
        'switches interpolation from BSpline-3 to NearestNeighbor for binary images (VOIs).'],...
        'HorizontalAlignment','left','FontSize',14);
    
    h.button_TfxPar = uicontrol(h.tab_Tfx,'Style','pushbutton','Tag','button_TfxPar',...
        'String','Parameters','Position',[0.01,0.82,0.2,0.05],'Callback',@self.UDtfx);
    h.text_TfxPar = uicontrol(h.tab_Tfx,'Style','text','Tag','text_TfxPar',...
        'Position',[0.22,0.79,0.77,0.1],'BackgroundColor','white','HorizontalAlignment','left');
    h.button_TfxOut = uicontrol(h.tab_Tfx,'Style','pushbutton','Tag','button_TfxOut',...
        'String','Output','Position',[0.01,0.71,0.2,0.05],'Callback',@self.UDtfx);
    h.text_TfxOut = uicontrol(h.tab_Tfx,'Style','text','Tag','text_TfxOut',...
        'Position',[0.22,0.68,0.77,0.1],'BackgroundColor','white','HorizontalAlignment','left');
    
    h.checkbox_TfxJac = uicontrol(h.tab_Tfx,'Style','checkbox','Tag','checkbox_TfxJac',...
        'String','| Jacobian |','Position',[0.01,0.62,0.3,0.05],'Callback',@self.UDtfx);
    h.checkbox_TfxJacmat = uicontrol(h.tab_Tfx,'Style','checkbox','Tag','checkbox_TfxJacmat',...
        'String','Jacobian Matrices','Position',[0.35,0.62,0.3,0.05],'Callback',@self.UDtfx);
    h.checkbox_TfxDef = uicontrol(h.tab_Tfx,'Style','checkbox','Tag','checkbox_TfxDef',...
        'String','Deformations','Position',[0.69,0.62,0.3,0.05],'Callback',@self.UDtfx);
    
    h.button_TfxAdd = uicontrol(h.tab_Tfx,'Style','pushbutton','Tag','button_TfxAdd',...
        'String','Add','Position',[0.02,0.56,0.2,0.05],'Callback',@self.UDtfx);
    h.button_TfxRemove = uicontrol(h.tab_Tfx,'Style','togglebutton','Tag','button_TfxRemove',...
        'String','Remove','Position',[0.23,0.56,0.2,0.05],'Callback',@self.UDtfx);
    h.button_TfxSTART = uicontrol(h.tab_Tfx,'Style','pushbutton','Tag','button_TfxSTART',...
        'String','START','Position',[0.78,0.56,0.2,0.05],'BackgroundColor',[0.5,1,1],...
        'Callback',@self.runTfx);
    
    h.table_Tfx = uitable(h.tab_Tfx,'Tag','table_Tfx','CellEditCallback',@self.UDtfx,...
        'Position',[0.01,0.01,0.98,0.54],'ColumnName',{'VOI','FileName','Directory'},...
        'ColumnWidth',{30,500,1000},'ColumnFormat',{'logical','char','char'},...
        'ColumnEditable',[true,false,false]);
    
self.h = h;
end

