function [img,res] = Module_YACTA(img,opts,res)


% Return function info for GUI and processing options
if nargin==0
    img = struct('title', {'YACTA'},...
                 'chk',   {true},...
                 'local',{true},...
                 'depend',{{}},...
                 'opts',  {[]});
    return;
end

if img(2).flag
    ydir = fullfile(procdir,['yacta_',ID,'_Ins']);
    writeLog(opts.fn_log,'YACTA directory: %s\n',ydir);
    airway_res = readYACTAairways(ydir);
    if isempty(airway_res)
        writeLog(opts.fn_log,'   FAILED to read YACTA results.\n')
    else
        % Initialize table
        T = table('Size',[Nr,1],'VariableTypes',{'cellstr'},'VariableNames',{'ROI'});
        T.ROI = regionnames';
        T.Properties.RowNames = regionnames;

        if isfield(airway_res,'Wall_pct__3_8_')
            T = addTableVarVal(T,'WallPct_3_8','WholeLung',airway_res.Wall_pct__3_8_);
        end

        fld = {'Wall_pct', '%0.2f' , {'Wall_pct',                     'WholeLung';...
                                      'Wall_pct_RightUpperLobe',      'RUL';...
                                      'Wall_pct_RightMidLobe',        'RML';...
                                      'Wall_pct_RightUpperLobePlus',  'RULplus';...
                                      'Wall_pct_RightLowerLobe',      'RLL';...
                                      'Wall_pct_LeftUpperLobe',       'LUL';...
                                      'Wall_pct_LeftUpperLobePlus',   'LULplus';...
                                      'Wall_pct_LeftLingula',         'LLi';...
                                      'Wall_pct_LeftLowerLobe',       'LLL'};...
               'Pi10', '%0.2f' ,     {'Pi10',         'WholeLung';...
                                      'Pi10_RUL',     'RUL';...
                                      'Pi10_RML',     'RML';...
                                      'Pi10_RULplus', 'RULplus';...
                                      'Pi10_RLL',     'RLL';...
                                      'Pi10_LUL'      'LUL';...
                                      'Pi10_LULplus'  'RULplus';...
                                      'Pi10_LLi',     'LLi';...
                                      'Pi10_LLL',     'LLL'};...
               'Pi15', '%0.2f' ,     {'Pi15',         'WholeLung'};...
               'BEI',  '%0.2f' ,     {'BEI_Lung',     'WholeLung';...
                                      'BEI_Right',    'RL';...
                                      'BEI_Left',     'LL';...
                                      'BEI_RUL',      'RUL';...
                                      'BEI_RML',      'RML';...
                                      'BEI_RULplus',  'RULplus';...
                                      'BEI_RLL',      'RLL';...
                                      'BEI_LUL',      'LUL';...
                                      'BEI_LULplus',  'LULplus';...
                                      'BEI_LLi',      'LLi';...
                                      'BEI_LLL',      'LLL'};...
               'BEI_gen', '%0.0f' ,  {'x1_Level_Lung',    'WholeLung';...
                                      'x1_Level_Right',   'RL';...
                                      'x1_Level_Left',    'LL';...
                                      'x1_Level_RUL',     'RUL';...
                                      'x1_Level_RML',     'RML';...
                                      'x1_Level_RULplus', 'RULplus';...
                                      'x1_Level_RLL',     'RLL';...
                                      'x1_Level_LUL',     'LUL';...
                                      'x1_Level_LLi',     'LLi';...
                                      'x1_Level_LULplus', 'LULplus';...
                                      'x1_Level_LLL',     'LLL'}};
        for icol = 1:size(fld,1)
            for ifld = 1:size(fld{icol,3},1)
                if isfield(airway_res,fld{icol,3}{ifld,1})
                    T = addTableVarVal(T,fld{icol,1},fld{icol,3}{ifld,2},airway_res.(fld{icol,3}{ifld,1}));
                end
            end
        end

        genstr = {'WT'};
        segstr = { 'seg',   4   ;...
                   'subseg',5:7 };
        lobestr =  {'Lung','Right','Left','RUL','RML','RUL+','RLL','LUL','LUL+','LLi','LLL'};
        lobestr2 = {'WholeLung','RL','LL','RUL','RML','RULplus','RLL','LUL','LULplus','LLi','LLL'};
        for i = 1:numel(genstr)
            if isfield(airway_res,genstr{i})
                for j = 1:size(segstr,1)
                    for k = 1:numel(lobestr)
                        if any(ismember(airway_res.(genstr{i}).Properties.VariableNames,lobestr{k}))
                            segind = segstr{j,2};
                            vals = airway_res.(genstr{i}).(lobestr{k});
                            vals = vals(segind(segind<=numel(vals)));
                            T = addTableVarVal(T,[genstr{i},'_',segstr{j,1}],lobestr2{k},mean(vals(vals>0)));
                        end
                    end
                end
            end
        end

    end
end

% Add table to results
res = addTableVarVal(res,T);
