function modules = CTlung_CheckDependencies(info,measures)

modules = struct('name',{'DicomConvert',...
                         'SegmentationExp',...
                         'SegmentationIns',...
                         'VesselSeg',...
                         'UnregStats',...
                         'Registration',...
                         'PRM',...
                         'tPRM'},...
                 'in',{ "dicom",...
                        "exp",...
                        "ins",...
                       ["ins","ins_seg"],...
                       ["exp","ins","exp_seg","ins_seg"],...
                       ["exp","ins","exp_seg","ins_seg"],...
                       ["exp","ins_R","exp_seg"],...
                       ["prm","exp_seg"]},...
                 'out',{["exp","ins"],...
                         "exp_seg",...
                         "ins_seg",...
                         "csa",...
                         "",...
                        ["ins_R","jac"],...
                         "prm",...
                         "tprm"},...
                 'proc',num2cell(false(1,8)));


             
             
for i = 1:length(measures)
    ind = cellfun(@(x)ismember(measures(i),x),{modules.out});
    inputs = modules(ind).in;
    done = false;
    while ~done
        for j = 1:numel(inputs)
            % Check if input files exist:
            fn = getFileName(info,inputs(j));
        end
    end
end

function fname = getFileName(info,str)
    switch str
        case "dicom"
            fnames.dicom = info.
        case "exp"
        case "ins"
        case "exp_seg"
        case "ins_seg"
        case "csa"
        case "ins_R"
        case "jac"
        case "prm"
        case "tprm"
    end

