function modules = CTlung_CheckDependencies(info,measures)

modules = struct('name',{'SegmentationExp',...
                         'SegmentationIns',...
                         'VesselSeg',...
                         'UnregStats',...
                         'Registration',...
                         'PRM',...
                         'tPRM'},...
                 'in',{ "exp",...
                        "ins",...
                       ["ins","ins_seg"],...
                       ["exp","ins","exp_seg","ins_seg"],...
                       ["exp","ins","exp_seg","ins_seg"],...
                       ["exp","ins_R","exp_seg"],...
                       ["prm","exp_seg"]},...
                 'out',{ "exp_seg",...
                         "ins_seg",...
                         "csa",...
                         "",...
                        ["ins_R","jac"],...
                         "prm",...
                         "tprm"},...
                 'proc',num2cell(false(1,7)));

fn_base = fullfile(info.procdir,sprintf('%s_%s',info.id,info.tp));
             
             
for i = 1:length(measures)
    ind = cellfun(@(x)ismember(measures(i),x),{modules.out});
    inputs = modules(ind).in;
    done = false;
    while ~done
        for j = 1:numel(inputs)
            % Check if input files exist:
            switch inputs(j)
                case "exp"
                case "ins"
                case "exp_seg"
                case "ins_seg"
                case "csa"
                case "ins_R"
                case "jac"
                case "prm"
                case "tprm"
            end
            fn = fn_base + tagstr + info.ext;
        end
    end
end
