function [prm,info] = pipeline_PRM(exp,mask,insR,svname,erode_flag)

if nargin<5
    erode_flag = false;
end

%% Filter images - median
% Check for gapped EXP data
nslc = size(exp,3);
gapchk = nnz(squeeze(std(exp,0,[1,2]))) < nslc;
if gapchk
    % 2D filter
    for i = 1:nslc
        exp(:,:,i) = medfilt2(exp(:,:,i),[3 3]);
        insR(:,:,i) = medfilt2(insR(:,:,i),[3 3]);
    end
else
    % 3D filter
    exp = medfilt3(exp,[3 3 3]);
    insR = medfilt3(insR,[3 3 3]);
end

%% Extract values of interest
exp = exp(mask);
insR = insR(mask);

%% Erode mask based on image values
if erode_flag
    mask = exp<-250 & insR<-250;
    if gapchk
        SE = strel('disk',2);
    else
        SE = strel('sphere',2);
    end
    mask = imerode(mask,SE);
end

%% Generate PRM:
prm = PRMclass();
prm.setOpts('thresh',[ 2 1 0 -856 ;...
                       1 2 0 -950 ;...
                       1 2 1 -94  ;...
                       1 2 0 -810 ],...
            'cutoff',[ 1 -1024 -250 ;...
                       2 -1024 -250 ],...
            'prmmap',{ logical([1 1 0 0]), '1';...
                       logical([1 1 1 0]), '2';...
                       logical([0 1 1 0]), '3';...
                       logical([0 0 1 0]), '4';...
                       logical([0 0 0 0]), '5';...
                       logical([1 0 0 0]), '6';...
                       logical([0 1 0 0; 1 0 1 0]), '7';...
                       logical([1 1 0 1]), '8';...
                       logical([1 1 1 1]), '9';...
                       logical([0 1 1 1]), '10'},...
            'cmap',[ 0      1    0      ;...
                     0      1    0      ;...
                     1      1    0      ;...
                     1      0    0      ;...
                     1      0    0      ;...
                     1      1    1      ;...
                     1      0.6  0.7843 ;...
                     0.749  0    0.749  ;...
                     0.749  0    0.749  ;...
                     0.749  0    0.749  ],...
            'labels',{'Expiration (HU)','Inspiration (HU)'},...
            'filtchk', false,...
            'SPopts',struct('Xvex',1,'Yvec',2,'Xmin',-1000,'Ymin',-1000,...
                            'Xmax',-250,'Ymax',-250,'show',1,'Nmax',5000),...
            'statchk',false);
[labels,vals] = prm.calcPRM([exp,insR],1:2,2,{'Exp','Ins'},mask);
prm = int8(prm.mat);

%% Save scatterplot figure
if nargin==5
    pipeline_save_fig(img.prm.hfscatter,svname);
end

%% Add results to info:
info.regions = labels;
info.pct = vals*100;
