function [prm,info] = pipeline_PRM(exp,mask,insR,svname,gapchk)

if nargin<5
    gapchk = false(1,2);
end

%% Filter images - median
exp = prm_filt(exp,gapchk(1));
insR = prm_filt(insR,gapchk(2));

%% Extract values of interest
exp = exp(mask);
insR = insR(mask);

%% Generate PRM:
prm = PRMclass();
prm.setOpts('thresh',[ 2 1 0 -856 ;...
                       1 2 0 -950 ;...
                       1 2 1 -94  ;...
                       1 2 0 -810 ],...
            'cutoff',[ 1 -1024 -250 ;...
                       2 -1024 -250 ],...
            'prmmap',{ logical([1 1 0 0]), '1';...
                       logical([1 1 1 0]), '2';...
                       logical([0 1 1 0]), '3';...
                       logical([0 0 1 0]), '4';...
                       logical([0 0 0 0]), '5';...
                       logical([1 0 0 0]), '6';...
                       logical([0 1 0 0; 1 0 1 0]), '7';...
                       logical([1 1 0 1]), '8';...
                       logical([1 1 1 1]), '9';...
                       logical([0 1 1 1]), '10'},...
            'cmap',[ 0      1    0      ;...
                     0      1    0      ;...
                     1      1    0      ;...
                     1      0    0      ;...
                     1      0    0      ;...
                     1      1    1      ;...
                     1      0.6  0.7843 ;...
                     0.749  0    0.749  ;...
                     0.749  0    0.749  ;...
                     0.749  0    0.749  ],...
            'labels',{'Expiration (HU)','Inspiration (HU)'},...
            'filtchk', false,...
            'SPopts',struct('Xvex',1,'Yvec',2,'Xmin',-1000,'Ymin',-1000,...
                            'Xmax',-250,'Ymax',-250,'show',1,'Nmax',5000),...
            'statchk',false);
[labels,vals] = prm.calcPRM([exp,insR],1:2,2,{'Exp','Ins'},mask);

%% Save scatterplot figure
if nargin==4
    pipeline_save_fig(prm.hfscatter,svname);
end

%% Add results to info:
info.regions = labels;
info.pct = vals*100;

% Return PRM
prm = int8(prm.mat);


function img = prm_filt(img,gapchk)
if gapchk
    for i = 1:size(img,3)
        img(:,:,i) = medfilt2(img(:,:,i),[3 3]);
    end
else
    img = medfilt3(img,[3 3 3]);
end