#######################################################################################
# Jekyll site settings
title: Pulmonary Toolkit
author: Tom Doel
logo: assets/images/PTKLogo.jpg
description: >-
  Documentation for users of the TD Pulmonary Toolkit

#######################################################################################
# Jupyter Book settings

# Main page settings
footer_text: Pulmonary Toolkit documentation by Tom Doel

# Sidebar settings
show_sidebar: true                # Show the sidebar. Only set to false if your only wish to host a single page.
collapse_inactive_chapters: true # Whether to collapse the inactive chapters in the sidebar
collapse_inactive_sections: true  # Whether to collapse the sub-sections within a non-active section in the sidebar
sidebar_footer_text: Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
