function initializeDat(self)
% Reset "dat" structure:

self.dat = struct('ct_ref',   struct('tag',"exp.ct",'mat',[],'info',[],'srcpath',""),...
                  'ct_hom',   struct('tag',"ins.ct",'mat',[],'info',[],'srcpath',""),...
                  'seg_ref',  struct('tag',"exp.label",'mat',[],'yacta',""),...
                  'seg_hom',  struct('tag',"ins.label",'mat',[],'yacta',""),...
                  'scatnet',  struct('tag',"scatnet",'mat',[]),...
                  'vessels',  struct('tag',"vessels",'mat',[],'info',[]),...
                  'csa',      struct('tag',"csa",'mat',[]),...
                  'reg_hom',  struct('tag',"ins.reg",'mat',[]),...
                  'reg_seg',  struct('tag',"ins.seg.reg",'mat',[]),...
                  'jac',      struct('tag',"jac",'mat',[]),...
                  'prm',      struct('tag',"prm",'mat',[]),...
                  'tprm',     struct('tag',"tprm") );

              