function info = init_niftiinfo(label,voxsz,dtype,d,orient)

info = struct( 'Description',label,...
               'PixelDimensions',[voxsz,zeros(1,numel(d)-3)],...
               'Datatype',dtype,...
               'ImageSize',d,...
               'Version','NIfTI1',...
               'Qfactor',-1,...
               'SpaceUnits','Millimeter',...
               'TimeUnits','None',...
               'SliceCode','Unknown',...
               'FrequencyDimension',0,...
               'PhaseDimension',0,...
               'SpatialDimension',3);
if nargin==5
    info.Transform = affine3d(orient');
end